name: Feature Request
description: Request anything that you'd like to see on the engine, Stage Editor and 6k are still not added in this custom version just yet.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the base engine?
    validations:
      required: true
